import { Inter, Hind_Siliguri } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const hindSiliguriFont = Hind_Siliguri({subsets: ['latin'], weight: ['400']})

export const metadata = {
  title: "Labs ITE App Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#c9184a]">
      <body className={hindSiliguriFont.className}>{children}</body>
    </html>
  );
}
